/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StartYourProjectRouteImport } from './routes/start-your-project'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as ToolsBusinessChecklistRouteImport } from './routes/tools.business-checklist'
import { Route as ToolsGstCalculatorRouteImport } from './routes/tools.gst-calculator'
import { Route as ToolsProjectEstimatorRouteImport } from './routes/tools.project-estimator'
import { Route as ToolsServiceFinderRouteImport } from './routes/tools.service-finder'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StartYourProjectRoute = StartYourProjectRouteImport.update({
  id: '/start-your-project',
  path: '/start-your-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const ToolsBusinessChecklistRoute = ToolsBusinessChecklistRouteImport.update({
  id: '/business-checklist',
  path: '/business-checklist',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGstCalculatorRoute = ToolsGstCalculatorRouteImport.update({
  id: '/gst-calculator',
  path: '/gst-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsProjectEstimatorRoute = ToolsProjectEstimatorRouteImport.update({
  id: '/project-estimator',
  path: '/project-estimator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsServiceFinderRoute = ToolsServiceFinderRouteImport.update({
  id: '/service-finder',
  path: '/service-finder',
  getParentRoute: () => ToolsRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-your-project': typeof StartYourProjectRoute
  '/tools': typeof ToolsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/tools/business-checklist': typeof ToolsBusinessChecklistRoute
  '/tools/gst-calculator': typeof ToolsGstCalculatorRoute
  '/tools/project-estimator': typeof ToolsProjectEstimatorRoute
  '/tools/service-finder': typeof ToolsServiceFinderRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-your-project': typeof StartYourProjectRoute
  '/tools': typeof ToolsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/tools/business-checklist': typeof ToolsBusinessChecklistRoute
  '/tools/gst-calculator': typeof ToolsGstCalculatorRoute
  '/tools/project-estimator': typeof ToolsProjectEstimatorRoute
  '/tools/service-finder': typeof ToolsServiceFinderRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/start-your-project': typeof StartYourProjectRoute
  '/tools': typeof ToolsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/tools/business-checklist': typeof ToolsBusinessChecklistRoute
  '/tools/gst-calculator': typeof ToolsGstCalculatorRoute
  '/tools/project-estimator': typeof ToolsProjectEstimatorRoute
  '/tools/service-finder': typeof ToolsServiceFinderRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/solutions'
    | '/start-your-project'
    | '/tools'
    | '/work'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/tools/business-checklist'
    | '/tools/gst-calculator'
    | '/tools/project-estimator'
    | '/tools/service-finder'
    | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/solutions'
    | '/start-your-project'
    | '/tools'
    | '/work'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/tools/business-checklist'
    | '/tools/gst-calculator'
    | '/tools/project-estimator'
    | '/tools/service-finder'
    | '/work/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/solutions'
    | '/start-your-project'
    | '/tools'
    | '/work'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/tools/business-checklist'
    | '/tools/gst-calculator'
    | '/tools/project-estimator'
    | '/tools/service-finder'
    | '/work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
  StartYourProjectRoute: typeof StartYourProjectRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-your-project': {
      id: '/start-your-project'
      path: '/start-your-project'
      fullPath: '/start-your-project'
      preLoaderRoute: typeof StartYourProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/tools/business-checklist': {
      id: '/tools/business-checklist'
      path: '/business-checklist'
      fullPath: '/tools/business-checklist'
      preLoaderRoute: typeof ToolsBusinessChecklistRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/gst-calculator': {
      id: '/tools/gst-calculator'
      path: '/gst-calculator'
      fullPath: '/tools/gst-calculator'
      preLoaderRoute: typeof ToolsGstCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/project-estimator': {
      id: '/tools/project-estimator'
      path: '/project-estimator'
      fullPath: '/tools/project-estimator'
      preLoaderRoute: typeof ToolsProjectEstimatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/service-finder': {
      id: '/tools/service-finder'
      path: '/service-finder'
      fullPath: '/tools/service-finder'
      preLoaderRoute: typeof ToolsServiceFinderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

interface ToolsRouteChildren {
  ToolsBusinessChecklistRoute: typeof ToolsBusinessChecklistRoute
  ToolsGstCalculatorRoute: typeof ToolsGstCalculatorRoute
  ToolsProjectEstimatorRoute: typeof ToolsProjectEstimatorRoute
  ToolsServiceFinderRoute: typeof ToolsServiceFinderRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsBusinessChecklistRoute: ToolsBusinessChecklistRoute,
  ToolsGstCalculatorRoute: ToolsGstCalculatorRoute,
  ToolsProjectEstimatorRoute: ToolsProjectEstimatorRoute,
  ToolsServiceFinderRoute: ToolsServiceFinderRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
  StartYourProjectRoute: StartYourProjectRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
